name: Arduino CI with Arduino CLI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup folder structure
        run: sudo mkdir /tmp/Hydronium && sudo mv ./* /tmp/Hydronium/ && mv /tmp/Hydronium ./Hydronium
      - name: Print out a tree as a test
        run: sudo apt install tree && tree
      - name: Install Arduino CLI
        run: curl -fsSL https://raw.githubusercontent.com/arduino/arduino-cli/master/install.sh | sh
      
